# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Alessandro Trapasso
email: ale.trapasso8@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Alessandro Trapasso personal web page.
author: Alessandro Trapasso
tagline: Personal web page
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://alee08.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username:
github_username:  alee08
permalink: /blog/:title/

####################
# jekyll-seo
#twitter:
#  username:
#  card:
#facebook:
#  app_id: 1234
#  publisher: 1234
#  admins: 1234
logo:
social:
  name: Alessandro Trapasso
  links:
    #- https://twitter.com/
    #- https://www.facebook.com/
    - https://www.linkedin.com/in/alessandro-trapasso/
    - https://github.com/alee08
    #- https://keybase.io/
    #- https://scholar.google.it/
    #- https://dblp.uni-trier.de/
    #- https://orcid.org/
google-site-verification:
lang: en_US
####################

defaults:
  - scope:
      path: ""
    values:
      image:
  - scope:
      path: "_posts/**/*.pdf"
    values:
      sitemap: false
############
jquery:
  version: 3.5.1
  integrity: sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2
jqueryui:
  version: 1.12.1
popper:
  version: 1.16.1
  integrity: sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN
bootstrap:
  version: 4.6.0
  integrity: sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF
############

# Google services
#google_analytics: UA-162936928-1
google_analytics_measurements:
- 'G-PYV8T5NDKD'
#- 'G-DDYB9GX4XD'

# markdown: kramdown
theme: minima

plugins:
  - jekyll-relative-links
  - jekyll-postfiles
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-figure
  - jekyll/scholar
  - jekyll-regex-replace
  - jemoji
relative_links:
  enabled: true
  collections: false

kramdown:
  parse_block_html: true


scholar:
  style: _layouts/custom.csl
  source: assets/bibliography
  bibliography: bibliography.bib
  sort_by: year,month
  order: descending
  group_by: year
  group_order: descending
  details_dir: papers
  details_layout: bibpage.html
  details_link: DetailsToRemove
  repository: papers
  bibliography_template: bibliography
  bibliography_list_tag: div
  bibliography_item_tag: div
  #bibliography_template: <a href="/papers/{{entry.year}}/{{key}}.pdf">{{reference}}</a>


# enable features
enable_math: true
enable_google_analytics: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - Rakefile
  - ignore/

include:
  - _pages
  - _data

sass:
  sass_dir: _sass

